In [1]:
import pandas as pd
import folium
df = pd.read_csv('Sold_data.csv')

df.head()

,State,Status,Source,Price,Price Source,Acres,Price per Acre,Image URL,Days on Market,Zipcode,Latitude,Longitude,Sale Date,Age Days,Views,Saves,Zillow URL,Google Maps URL,DOM History
0,Tennessee,SOLD*,MLS,120000,listing,1.58,75949.0,https://photos.zillowstatic.com/fp/bd3979b9af9...,0.038044,37722.0,35.791615,-83.238785,NaN,14,13.0,2.0,https://www.zillow.com/homedetails/LOT-5-6-Ard...,https://www.google.com/maps/search/?api=1&quer...,"date: 2025-08-24, event: Listed for sale, pric..."
1,Tennessee,SOLD*,Public records,149999,listing,1.10,136363.0,https://photos.zillowstatic.com/fp/b51d651567c...,0.000000,37087.0,36.192420,-86.260345,NaN,14,14.0,0.0,https://www.zillow.com/homedetails/717-Peyton-...,https://www.google.com/maps/search/?api=1&quer...,NaN
2,Tennessee,SOLD*,Public records,229000,listing,10.00,22900.0,https://photos.zillowstatic.com/fp/a6309640a2c...,0.000000,37763.0,35.841280,-84.509220,NaN,14,93.0,7.0,https://www.zillow.com/homedetails/117-Hensley...,https://www.google.com/maps/search/?api=1&quer...,NaN
3,Tennessee,SOLD,MLS,530000,listing,15.52,34149.0,https://photos.zillowstatic.com/fp/ae33620617b...,401.000000,37062.0,35.994675,-87.182630,8/23/2025,15,NaN,NaN,https://www.zillow.com/homedetails/0-Crow-Cut-...,https://www.google.com/maps/search/?api=1&quer...,"date: 2025-08-23, event: Sold, price: 530000; ..."
4,Tennessee,SOLD*,Public records,75000,listing,0.25,300000.0,https://maps.googleapis.com/maps/api/staticmap...,0.000000,37415.0,35.107548,-85.282950,NaN,15,33.0,5.0,https://www.zillow.com/homedetails/3509-Sleepy...,https://www.google.com/maps/search/?api=1&quer...,NaN

In [2]:
# how many rows in df
len(df)

9845

In [3]:
# Remove any rows that might be missing location data
df.dropna(subset=['Latitude', 'Longitude'], inplace=True)

# how many rows remain
len(df)

9462

In [5]:
# Create a map, centered on the average coordinates of all 9462 locations
my_map = folium.Map(location=[df['Latitude'].mean(), df['Longitude'].mean()], zoom_start=9)

# Loop through your data and add a circle for each point
for idx, row in df.iterrows():
    # Create the text that will appear in the popup
    popup_text = f"Price: ${int(row['Price']):,}<br>Acres: {row['Acres']}"
    
    # Add a blue circle marker to the map
    folium.CircleMarker(
        location=[row['Latitude'], row['Longitude']],
        radius=1,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        popup=folium.Popup(popup_text, max_width=200)
    ).add_to(my_map)

my_map.save("all_sold.html")

In [6]:
# what kind of entries are the days on market (we want numbers, ie ints/floats)
df['Days on Market'].apply(type).value_counts()

Days on Market
<class 'float'>    9462
Name: count, dtype: int64

In [7]:
# filter the DataFrame
# "hot" properties defined as 2-5 acres on market for < 90 days (but more than 0)
acreage_filtered_df = df[(df['Days on Market'] > 0) & (df['Days on Market'] <= 90)].copy()
acreage_filtered_df = acreage_filtered_df[(acreage_filtered_df['Acres'] >= 2) & (acreage_filtered_df['Acres'] <= 10)].copy()

acreage_filtered_df.head()

,State,Status,Source,Price,Price Source,Acres,Price per Acre,Image URL,Days on Market,Zipcode,Latitude,Longitude,Sale Date,Age Days,Views,Saves,Zillow URL,Google Maps URL,DOM History
7,Tennessee,SOLD,MLS,76000,listing,2.54,29921.0,https://photos.zillowstatic.com/fp/f7ddeba3baf...,46.0,37743.0,36.099520,-82.978000,8/22/2025,16,NaN,NaN,https://www.zillow.com/homedetails/Bright-Hope...,https://www.google.com/maps/search/?api=1&quer...,"date: 2025-08-22, event: Sold, price: 76000; d..."
8,Tennessee,SOLD,MLS,130000,listing,5.53,23508.0,https://photos.zillowstatic.com/fp/6b998c1a1c6...,84.0,37743.0,36.175040,-82.911840,8/22/2025,16,NaN,NaN,https://www.zillow.com/homedetails/0-Marley-Dr...,https://www.google.com/maps/search/?api=1&quer...,"date: 2025-08-22, event: Sold, price: 130000; ..."
16,Tennessee,SOLD,MLS,51750,listing,5.75,9000.0,https://maps.googleapis.com/maps/api/staticmap...,17.0,37362.0,35.070350,-84.695370,8/22/2025,16,NaN,NaN,https://www.zillow.com/homedetails/0-Frey-Rd-O...,https://www.google.com/maps/search/?api=1&quer...,"date: 2025-08-22, event: Sold, price: 51750; d..."
45,Tennessee,SOLD,MLS,176000,listing,5.00,35200.0,https://photos.zillowstatic.com/fp/c33c45029f5...,50.0,37015.0,36.346985,-87.123820,8/22/2025,16,NaN,NaN,https://www.zillow.com/homedetails/2-Jim-Read-...,https://www.google.com/maps/search/?api=1&quer...,"date: 2025-08-22, event: Sold, price: 176000; ..."
56,Tennessee,SOLD,MLS,232500,listing,3.00,77500.0,https://photos.zillowstatic.com/fp/f347020c8b2...,41.0,37801.0,35.708923,-84.087494,8/21/2025,17,NaN,NaN,https://www.zillow.com/homedetails/1223-Walker...,https://www.google.com/maps/search/?api=1&quer...,"date: 2025-08-21, event: Sold, price: 232500; ..."

In [8]:
# Create a new map, centered on the average coordinates of your filtered data
map_of_hot_properties = folium.Map(location=[acreage_filtered_df['Latitude'].mean(), acreage_filtered_df['Longitude'].mean()], zoom_start=9)

# Loop through your filtered data and add a green circle for each property
for idx, row in acreage_filtered_df.iterrows():
    # Create the popup text, including Days on Market for verification
    popup_text = f"Price: ${int(row['Price']):,}<br>" \
                 f"Acres: {row['Acres']}<br>" \
                 f"Days on Market: {int(row['Days on Market'])}"
    
    # Add a green circle marker to the map to signify it's a "hot" property
    folium.CircleMarker(
        location=[row['Latitude'], row['Longitude']],
        radius=1,
        color='green',
        fill=True,
        fill_color='#28a745',
        popup=folium.Popup(popup_text, max_width=200)
    ).add_to(map_of_hot_properties)

map_of_hot_properties.save("hot_pockets.html")

In [9]:
import numpy as np
from sklearn.cluster import DBSCAN
import matplotlib.colors as mcolors

# convert to numpy array
coords = acreage_filtered_df[['Latitude', 'Longitude']].to_numpy()
coords_in_radians = np.radians(coords)

# > 15 properties within a 10-mile radius
radius = 10
samples = 15
dbscan = DBSCAN(
    eps=(radius/3959), 
    min_samples=samples, 
    algorithm='ball_tree', 
    metric='haversine')

# run the scan
cluster_labels = dbscan.fit_predict(coords_in_radians)
# assigned a cluster (-1 for noise)
acreage_filtered_df['cluster'] = cluster_labels

# Create the map with the new clusters
final_map = folium.Map(location=[acreage_filtered_df['Latitude'].mean(), acreage_filtered_df['Longitude'].mean()], zoom_start=9)
unique_clusters = acreage_filtered_df['cluster'][acreage_filtered_df['cluster'] != -1].unique()
colors = list(mcolors.TABLEAU_COLORS.values()) * 10

for cluster_id in unique_clusters:
    cluster_points = acreage_filtered_df[acreage_filtered_df['cluster'] == cluster_id]
    center_lat = cluster_points['Latitude'].mean()
    center_lon = cluster_points['Longitude'].mean()
    
    folium.Circle(
        location=[center_lat, center_lon],
        radius=radius * 1609,        # miles in meters
        color=colors[cluster_id],
        fill=True,
        fill_opacity=0.2,
        popup=f"Hot Pocket #{cluster_id}<br>{len(cluster_points)} properties"
    ).add_to(final_map)
    
    for idx, row in cluster_points.iterrows():
        folium.CircleMarker(
            location=[row['Latitude'], row['Longitude']],
            radius=1,
            color=colors[cluster_id],
            fill=True,
            fill_color=colors[cluster_id],
            fill_opacity=0.8
        ).add_to(final_map)

# set the rigth zoom
final_map.fit_bounds(final_map.get_bounds())
final_map.save("clusters.html")

In [23]:
# tennessee df
tennessee_df = acreage_filtered_df[
    (acreage_filtered_df['cluster'] != -1) &
    (acreage_filtered_df['State'] == 'Tennessee')
].copy()

# two different df by above/below 5 acres
tennessee_df_lt_5 = tennessee_df[tennessee_df['Acres'] <= 5].copy()
tennessee_df_gt_5 = tennessee_df[tennessee_df['Acres'] > 5].copy()

# check lengths
len(tennessee_df), len(tennessee_df_lt_5), len(tennessee_df_gt_5)

(15, 6, 9)

In [ ]:
# alabama df
alabama_df = acreage_filtered_df[
    (acreage_filtered_df['cluster'] != -1) &
    (acreage_filtered_df['State'] == 'Alabama')
].copy()

# two different df by above/below 5 acres
alabama_df_lt_5 = alabama_df[(alabama_df['Acres'] <= 5)].copy()
alabama_df_gt_5 = alabama_df[(alabama_df['Acres'] > 5)].copy()

# check lengths
len(alabama_df), len(alabama_df_lt_5), len(alabama_df_gt_5)

(34, 27, 7)

In [26]:
# decided to use alabama_lt_5
alabama_df_lt_5['Price per Acre'].mean().round()

52124.0